export { default as Registration } from './RegistrationScreen'
export { default as Login } from './LoginScreen'
export { default as Home } from './Home'
export { default as CreatePosts } from './CreatePostsScreen'
export { default as Posts } from './PostsScreen'
export { default as Profile } from './ProfileScreen'
